mixed-port: 7890
unified-delay: false
geodata-mode: true
tcp-concurrent: false
find-process-mode: strict
global-client-fingerprint: chrome

allow-lan: true
mode: rule
log-level: info
ipv6: true

external-controller: 127.0.0.1:9090
#external-ui: ui
secret: ""

geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: false
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  #prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - localhost.ptlogin2.qq.com
  default-nameserver:
    - 223.5.5.5
  nameserver:
      - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query

p: &p
  {type: http, interval: 42300, health-check: {enable: true, url: http://cp.cloudflare.com/generate_204, interval: 300}}

f: &f
  {type: select, proxies: [Proxy, Auto, Fallback, HongKong, TaiWan, Singapore, Japan, America, Others, DIRECT]}

d: &d
  {type: select, proxies: [DIRECT, Proxy, Auto, Fallback, HongKong, TaiWan, Singapore, Japan, America, Others]}

proxies:

s: &s
  type: select
  use:
  - MySubs

proxy-providers:
  MySubs:
    <<: *p
    url: ""
    path: ./MySubs.yaml

proxy-groups:

  - {name: Final, type: select, proxies: [Proxy]}

  - {name: Proxy, type: select, proxies: [Auto, Fallback, Others]}

  - {name: Auto, <<: *s, tolerance: 2, type: url-test}

  - {name: Fallback, <<: *s, type: fallback}

  - {name: Foreign, <<: *f}

  - {name: Domestic, <<: *d}

  - {name: BiliBili, <<: *d}

  - {name: Spotify, <<: *f}

  - {name: TikTok, <<: *f}

  - {name: OpenAI, <<: *f}

  - {name: Telegram, <<: *f}

  - {name: Apple, <<: *d}

  - {name: Microsoft, <<: *d}

  - {name: AdBlock, type: select, proxies: [REJECT, DIRECT]}


  - {name: HongKong, <<: *s, filter: "æ¸¯|ðŸ‡­ðŸ‡°|HK|(?i)Hong"}

  - {name: TaiWan, <<: *s, filter: "å°|ðŸ‡¨ðŸ‡³|ðŸ‡¹ðŸ‡¼|æ¹¾|TW|(?i)Taiwan"}

  - {name: Singapore, <<: *s, filter: "æ–°åŠ å¡|å¡|ç‹®åŸŽ|ðŸ‡¸ðŸ‡¬|SG|(?i)Singapore"}

  - {name: Japan, <<: *s, filter: "æ—¥|ðŸ‡¯ðŸ‡µ|ä¸œäº¬|JP|(?i)Japan"}

  - {name: America, <<: *s, filter: "ç¾Ž|ðŸ‡ºðŸ‡²|US|(?i)States|American"}

  - {name: Others, type: select, proxies: [DIRECT], <<: *s}

rules:
  - GEOSITE,category-ads-all,AdBlock
  - GEOSITE,private,DIRECT
  - GEOSITE,openai,OpenAI
  - GEOSITE,github,Proxy
  - GEOSITE,bilibili,BiliBili
  - GEOSITE,spotify,Spotify
  - GEOSITE,tiktok,TikTok
  - GEOSITE,telegram,Telegram
  - GEOSITE,apple,Apple
  - GEOSITE,microsoft,Microsoft
  - GEOSITE,geolocation-!cn,Foreign
  - GEOSITE,cn,Domestic

  - GEOIP,netflix,Foreign
  - GEOIP,telegram,Telegram
  - GEOIP,private,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Final
