# Stash Config Make by Coldvvater
# TG Channel: https://t.me/Ison_Channel
# GitHubä¸»é¡µ: https://github.com/Coldvvater
# Update Date: 2022.08.25
---
subscribe-url: ä½ çš„è®¢é˜…é“¾æ¥
# æ›¿æ¢ä¸Šé¢æ–‡å­—ç”¨äºStashè·å–æœºåœºæµé‡ä¿¡æ¯å¹¶åœ¨ä¸»é¡µæ˜¾ç¤º

mixed-port: 7890
  # æœ¬åœ°æ··åˆä»£ç†(httpå’Œsocks5åˆå¹¶ï¼‰ç«¯å£
allow-lan: true
  # å…è®¸å±€åŸŸç½‘è¿æ¥(false/true)
bind-address:
  # ç›‘å¬IPç™½åå•ï¼ˆå½“allow-lanï¼štrueï¼‰ï¼Œåªå…è®¸åˆ—è¡¨è®¾å¤‡
  '*'
  # å…¨éƒ¨è®¾å¤‡
  # 192.168.122.11
  #å•ä¸ªip4åœ°å€
  # "[aaaa::a8aa:ff:fe09:57d8]"
  #å•ä¸ªip6åœ°å€
mode: rule
  # clashå·¥ä½œæ¨¡å¼ï¼ˆrule/global/directï¼‰
log-level: debug
  # æ—¥å¿—ç­‰çº§ï¼ˆinfo/warning/error/debug/silentï¼‰
external-controller: 127.0.0.1:9090
  # æ§åˆ¶å™¨ç›‘å¬åœ°å€
dns:
  enable: true
  # DNSå¼€å…³(false/true)
  listen: 0.0.0.0:53
  # DNSç›‘å¬åœ°å€
  ipv6: false
  # IP6è§£æå¼€å…³ï¼›å¦‚æœä¸ºfalseï¼Œå°†è¿”å›ip6ç»“æœä¸ºç©º
  default-nameserver:
  # è§£æéIPçš„dnsç”¨çš„dnsæœåŠ¡å™¨,åªæ”¯æŒçº¯IP
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  # DNSæ¨¡å¼(redir-host/fake-ip)
  fake-ip-range: 198.18.0.1/16
  # Fake-IPè§£æåœ°å€æ± 
  fake-ip-filter:
  # Fake-ipè¿‡æ»¤ï¼Œåˆ—è¡¨ä¸­çš„åŸŸåè¿”å›çœŸå®ip
  # Stun Services
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
  # Google Voices
    - 'lens.l.google.com'
  # Nintendo Switch
    - '*.n.n.srv.nintendo.net'
  # PlayStation
    - '+.stun.playstation.net'
  # XBox
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
  # Microsoft
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
  # Bilibili CDN
    - '*.mcdn.bilivideo.cn'
  nameserver:
  # é»˜è®¤DNSæœåŠ¡å™¨ï¼Œæ”¯æŒudp/tcp/dot/doh/doq
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    
proxy-providers:

  All:
    type: http
    url: ""
    # å¼ºçƒˆæ¨èä½ ä½¿ç”¨Clashç±»å‹è®¢é˜…é“¾æ¥æˆ–Sub-Storeè½¬æ¢è®¢é˜…é“¾æ¥å¡«å…¥å¼•å·""å†…ä½¿ç”¨ã€‚
    # PSï¼šå¦‚æœºåœºæ²¡æœ‰Clashç±»å‹é“¾æ¥ï¼Œå¯å°è¯•ä½¿ç”¨é€šç”¨è®¢é˜…é“¾æ¥ï¼Œå¦‚ä»æœªè§£å†³ï¼Œå¯é€šè¿‡Sub-Storeæˆ–ACL4SSRç­‰è¿›è¡Œè®¢é˜…è½¬æ¢ã€‚
    interval: 3600
    path: ./all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
    
proxies:
  # æœ¬åœ°æœåŠ¡å™¨

proxy-groups:
  # ç­–ç•¥ç»„

  - name: Final # æ¼ç½‘ä¹‹é±¼
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Final.png
    proxies:
      - Proxy

  - name: Proxy # èŠ‚ç‚¹é€‰æ‹©
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Rocket.png
    proxies:
      - Auto
      - Others

  - name: Auto # è‡ªåŠ¨ç­›é€‰
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Auto.png
    use: 
       - All
    url: "http://www.gstatic.com/generate_204"
    interval: 300

  - name: Global # å…¨çƒåŠ é€Ÿ
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Global.png
    proxies: &G
      - Proxy
      - Auto
      - HongKong
      - TaiWan
      - Singapore
      - Japan
      - America
      - Others
      - DIRECT

  - name: China # å›½å†…ç½‘ç«™
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/China_Map.png
    proxies: &C
      - DIRECT
      - Proxy
      - Auto
      - HongKong
      - TaiWan
      - Singapore
      - Japan
      - America
      - Others

  - name: BiliBili # å“”å“©å“”å“©
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/bilibili.png
    proxies:
      *C

  - name: Spotify # å£°ç”°éŸ³ä¹
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Spotify.png
    proxies:
      *G

  - name: Streaming # å›½é™…åª’ä½“
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/GlobalMedia.png
    proxies:
      *G

  - name: Telegram # ç”µæŠ¥ä¿¡æ¯
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Telegram_X.png
    proxies:
      *G

  - name: Apple # è‹¹æœæœåŠ¡
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Apple.png
    proxies:
      *C

  - name: Microsoft # å¾®è½¯æœåŠ¡
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Microsoft.png
    proxies:
      *C

  - name: ADblock # å¹¿å‘Šæ‹¦æˆª
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Advertising.png
    proxies:
      - REJECT
      - DIRECT

  - name: HongKong # é¦™æ¸¯èŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Hong_Kong.png
    use:
      - All
    filter: (?=.*(æ¸¯|ğŸ‡­ğŸ‡°|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|ç¾)).)*$
    
  - name: TaiWan # å°æ¹¾èŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/China.png
    use:
      - All
    filter: (?=.*(å°|ğŸ‡¨ğŸ‡³|ğŸ‡¹ğŸ‡¼|TW|(?i)Taiwan))^((?!(æ¸¯|æ—¥|éŸ©|æ–°|ç¾)).)*$
         
  - name: Singapore # ç‹®åŸèŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Singapore.png
    use:
      - All
    filter: (?=.*(å¡|ğŸ‡¸ğŸ‡¬|SG|(?i)Singapore))^((?!(æ¸¯|å°|æ—¥|éŸ©|ç¾)).)*$
    
  - name: Japan # æ—¥æœ¬èŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Japan.png
    use:
      - All
    filter: (?=.*(æ—¥|ğŸ‡¯ğŸ‡µ|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$

  - name: America # ç¾å›½èŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/United_States.png
    use:
      - All
    filter: (?=.*(ç¾|ğŸ‡ºğŸ‡¸|US|(?i)States|American))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$

  - name: Others # å…¶ä»–èŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Airport.png
    use: 
       - All

rule-providers:
  # è¿œç¨‹è§„åˆ™é›†

  Unbreak: # è§„åˆ™ä¿®æ­£
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    path: ./ruleset/Unbreak.yaml
    interval: 86400

  AD-Ban: # å¹¿å‘Šæ‹¦æˆª
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/Coldvvater/Clash/master/RuleSet/AD-Ban.yaml
    path: ./ruleset/AD-Ban.yaml
    interval: 86400

  Privacy: # éšç§ä¿æŠ¤
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/Coldvvater/Clash/master/RuleSet/Privacy.yaml
    path: ./ruleset/Privacy.yaml
    interval: 86400

  Hijacking: # è¿è¥åŠ«æŒ
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml
    path: ./ruleset/Hijacking.yaml
    interval: 86400

  BiliBili: # å“”å“©å“”å“©
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/Coldvvater/Clash/master/RuleSet/bilibili.yaml
    path: ./ruleset/BiliBili.yaml
    interval: 86400

  Spotify: # å£°ç”°éŸ³ä¹
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml
    path: ./ruleset/Spotify.yaml
    interval: 86400

  YouTube: # æ²¹ç®¡è§†é¢‘
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
    path: ./ruleset/YouTube.yaml
    interval: 86400

  Streaming: # å›½é™…åª’ä½“
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml
    path: ./ruleset/Streaming.yaml
    interval: 86400

  Telegram: # ç”µæŠ¥ä¿¡æ¯
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
    path: ./ruleset/Telegram.yaml
    interval: 86400

  Twitter: # æ¨ç‰¹åˆ†æµ
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml
    path: ./ruleset/twitter.yaml
    interval: 86400

  Google: # è°·æ­Œåˆ†æµ
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml
    path: ./ruleset/Google.yaml
    interval: 86400

  Github: # Github
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
    path: ./ruleset/Github.yaml
    interval: 86400

  Global: # å›½å¤–ç½‘ç«™
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyLite.yaml
    path: ./ruleset/Global.yaml
    interval: 86400

  Apple: # è‹¹æœæœåŠ¡
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml
    path: ./ruleset/Apple.yaml
    interval: 86400

  Microsoft: # å¾®è½¯æœåŠ¡
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  China: # å›½å†…ç½‘ç«™
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml
    path: ./ruleset/China.yaml
    interval: 86400

  LAN: # å±€åŸŸç½‘
    type: http
    behavior: classical
    url: https://raw.githubusercontents.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml
    path: ./ruleset/Lan.yaml
    interval: 86400

  ASN-CN: # IP-ASNè§„åˆ™
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/Coldvvater/Clash/master/RuleSet/ASN_China.yaml
    path: ./ruleset/ASN-CN.yaml
    interval: 86400

rules:
  # æœ¬åœ°è§„åˆ™
  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,AD-Ban,ADblock
  - RULE-SET,Privacy,ADblock
  - RULE-SET,Hijacking,ADblock
  - RULE-SET,BiliBili,BiliBili
  - RULE-SET,Spotify,Spotify
  - RULE-SET,Streaming,Streaming
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Twitter,Global
  - RULE-SET,Google,Global
  - RULE-SET,Github,Global
  - RULE-SET,Global,Global
  - RULE-SET,Apple,Apple
  - RULE-SET,Microsoft,Global
  # - RULE-SET,China,China
  - RULE-SET,LAN,DIRECT
  - RULE-SET,ASN-CN,DIRECT
  # - GEOIP,CN,China
  - MATCH,Final
