# Clash Config Make by Coldvvater
# TG Channel: https://t.me/Ison_Channel
# GitHubä¸»é¡µ: https://github.com/Coldvvater
# Update Date: 2022.06.16

subscribe-url: ä½ çš„è®¢é˜…é“¾æ¥
# æ›¿æ¢ä¸Šé¢æ–‡å­—ç”¨äºStashè·å–æœºåœºæµé‡ä¿¡æ¯å¹¶åœ¨ä¸»é¡µæ˜¾ç¤º

mixed-port: 7890
  # æœ¬åœ°æ··åˆä»£ç†(httpå’Œsocks5åˆå¹¶ï¼‰ç«¯å£
allow-lan: true
  # å…è®¸å±€åŸŸç½‘è¿æ¥(false/true)
bind-address:
  # ç›‘å¬IPç™½åå•ï¼ˆå½“allow-lanï¼štrueï¼‰ï¼Œåªå…è®¸åˆ—è¡¨è®¾å¤‡
  '*'
  # å…¨éƒ¨è®¾å¤‡
  # 192.168.122.11
  #å•ä¸ªip4åœ°å€
  # "[aaaa::a8aa:ff:fe09:57d8]"
  #å•ä¸ªip6åœ°å€
mode: rule
  # clashå·¥ä½œæ¨¡å¼ï¼ˆrule/global/directï¼‰
log-level: debug
  # æ—¥å¿—ç­‰çº§ï¼ˆinfo/warning/error/debug/silentï¼‰
external-controller: 127.0.0.1:9090
  # æ§åˆ¶å™¨ç›‘å¬åœ°å€
dns:
  enable: true
  # DNSå¼€å…³(false/true)
  listen: 0.0.0.0:53
  # DNSç›‘å¬åœ°å€
  ipv6: false
  # IP6è§£æå¼€å…³ï¼›å¦‚æœä¸ºfalseï¼Œå°†è¿”å›ip6ç»“æœä¸ºç©º
  default-nameserver:
  # è§£æéIPçš„dnsç”¨çš„dnsæœåŠ¡å™¨,åªæ”¯æŒçº¯IP
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  # DNSæ¨¡å¼(redir-host/fake-ip)
  fake-ip-range: 198.18.0.1/16
  # Fake-IPè§£æåœ°å€æ± 
  fake-ip-filter:
  # Fake-ipè¿‡æ»¤ï¼Œåˆ—è¡¨ä¸­çš„åŸŸåè¿”å›çœŸå®ip
    - '*.lan'
    - '+.cn'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - '*.alipay.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'msftconnecttest.com'
    - 'msftncsi.com'
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - 'xnotify.xboxlive.com'
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    - 'proxy.golang.org'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    - 'lens.l.google.com'
    - 'stun.l.google.com'
    - '+.nflxvideo.net'
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.mcdn.bilivideo.cn'
    - 'dl.google.com'
  nameserver:
  # é»˜è®¤DNSæœåŠ¡å™¨ï¼Œæ”¯æŒudp/tcp/dot/doh/doq
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    
proxy-providers:

  #å…¨éƒ¨èŠ‚ç‚¹
  All: &All #å»ºç«‹é”šç‚¹
    type: http
    url: ""
    # å¼ºçƒˆæ¨èä½ ä½¿ç”¨Clashç±»å‹è®¢é˜…é“¾æ¥æˆ–Sub-Storeè½¬æ¢è®¢é˜…é“¾æ¥å¡«å…¥å¼•å·""å†…ä½¿ç”¨ã€‚
    # PSï¼šå¦‚æœºåœºæ²¡æœ‰Clashç±»å‹é“¾æ¥ï¼Œå¯å°è¯•ä½¿ç”¨é€šç”¨è®¢é˜…é“¾æ¥ï¼Œå¦‚ä»æœªè§£å†³ï¼Œå¯é€šè¿‡Sub-Storeæˆ–ACL4SSRç­‰è¿›è¡Œè®¢é˜…è½¬æ¢ã€‚
    interval: 3600
    path: ./all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
    
  #é¦™æ¸¯èŠ‚ç‚¹
  HK:
    <<: *All #å¼•ç”¨é”šç‚¹å†…å®¹
    filter: æ¸¯|ğŸ‡­ğŸ‡°|HK|(?i)Hong
 
  #å°æ¹¾èŠ‚ç‚¹
  TW:
    <<: *All
    filter: å°|ğŸ‡¨ğŸ‡³|ğŸ‡¹ğŸ‡¼|æ¹¾|TW|(?i)Taiwan
   
  #ç‹®åŸèŠ‚ç‚¹
  SG:
    <<: *All
    filter: æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|SG|(?i)Singapore
    
  #æ—¥æœ¬èŠ‚ç‚¹
  JP:
    <<: *All
    filter: æ—¥|ğŸ‡¯ğŸ‡µ|ä¸œäº¬|JP|(?i)Japan
    
  #ç¾å›½èŠ‚ç‚¹    
  US:
    <<: *All
    filter: ç¾|ğŸ‡ºğŸ‡²|US|(?i)States|American
    
proxies:
            
proxy-groups:

  - name: èŠ‚ç‚¹é€‰æ‹©
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Rocket.png
    use:
      - All
    proxies:
      - è‡ªåŠ¨ç­›é€‰
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - DIRECT

  - name: è‡ªåŠ¨ç­›é€‰
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Auto.png
    use: 
       - All
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    
  - name: è‹¹æœæœåŠ¡
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Apple.png
    proxies:
      - DIRECT
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹

  - name: æ¸¯å°ç•ªå‰§
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/bilibili.png
    proxies:
      - DIRECT
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹

  - name: å›½é™…åª’ä½“
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/GlobalMedia.png
    proxies:
      - èŠ‚ç‚¹é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
    
  - name: æ¼ç½‘ä¹‹é±¼
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/YoYu.png
    proxies:
      - èŠ‚ç‚¹é€‰æ‹©
      - è‡ªåŠ¨ç­›é€‰
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - DIRECT

  - name: é¦™æ¸¯èŠ‚ç‚¹
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/HK.png
    use:
      - HK
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    
  - name: å°æ¹¾èŠ‚ç‚¹
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/TW.png
    use:
      - TW
    url: "http://www.gstatic.com/generate_204"
    interval: 300
         
  - name: ç‹®åŸèŠ‚ç‚¹
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/SG.png
    use:
      - SG
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    
  - name: æ—¥æœ¬èŠ‚ç‚¹
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/JP.png
    use:
      - JP
    url: "http://www.gstatic.com/generate_204"
    interval: 300

  - name: ç¾å›½èŠ‚ç‚¹
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/US.png
    use:
      - US
    url: "http://www.gstatic.com/generate_204"
    interval: 300

rule-providers:

  Unbreak:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    path: ./ruleset/Unbreak.yaml
    interval: 86400

  AD-Ban:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/Coldvvater/Clash/master/RuleSet/AD-Ban.yaml
    path: ./ruleset/AD-Ban.yaml
    interval: 86400

  Privacy:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/Coldvvater/Clash/master/RuleSet/Privacy.yaml
    path: ./ruleset/Privacy.yaml
    interval: 86400

  Hijacking:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml
    path: ./ruleset/Hijacking.yaml
    interval: 86400

  Streaming:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    path: ./ruleset/Streaming.yaml
    interval: 86400

  StreamingSE:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    path: ./ruleset/StreamingSE.yaml
    interval: 86400

  Global:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    path: ./ruleset/Global.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Apple/Apple.yaml
    path: ./ruleset/Apple.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    path: ./ruleset/China.yaml
    interval: 86400

  LAN:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml
    path: ./ruleset/Lan.yaml
    interval: 86400

rules:
  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,AD-Ban,REJECT
  - RULE-SET,Privacy,REJECT
  - RULE-SET,Hijacking,REJECT
  - RULE-SET,Streaming,å›½é™…åª’ä½“
  - RULE-SET,StreamingSE,æ¸¯å°ç•ªå‰§
  - RULE-SET,Global,èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,Apple,è‹¹æœæœåŠ¡
  - RULE-SET,China,DIRECT
  - RULE-SET,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,æ¼ç½‘ä¹‹é±¼
