# A Lazy_Congfg for Stash Make by Coldvvater
# 2022.06.05
subscribe-url: ä½ çš„è®¢é˜…é“¾æ¥
# æ›¿æ¢ä¸Šé¢æ–‡å­—ç”¨äºStashè·å–æœºåœºæµé‡ä¿¡æ¯å¹¶åœ¨ä¸»é¡µæ˜¾ç¤º
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: rule
log-level: silent
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '+.cn'
    - 'time1.cloud.tencent.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - '*.mcdn.bilivideo.cn'
    - '*.localhost'
    - localhost.ptlogin2.qq.com
    - '+.baidu.com'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '*.alipay.com'
    - 'dl.google.com'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    
proxy-providers:

  #å…¨éƒ¨èŠ‚ç‚¹
  All: &All #å»ºç«‹é”šç‚¹
    type: http
    url: ""
    # å°†Clashç±»å‹è®¢é˜…é“¾æ¥ç²˜è´´åœ¨å¼•å·""å†…ï¼Œå¤šä¸ªé“¾æ¥ä½¿ç”¨è‹±æ–‡ç¬¦å·çš„ç«–æ |éš”å¼€ä¸€èµ·å¡«ä¸Šå³å¯ï¼Œ
    # å¦‚è®¢é˜…é“¾æ¥ä¸æ”¯æŒproxy-providersï¼Œè¯·å…ˆè¿›è¡Œè®¢é˜…è½¬æ¢ã€‚
    interval: 3600
    path: ./all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
    
  #é¦™æ¸¯èŠ‚ç‚¹
  HK:
    <<: *All #å¼•ç”¨é”šç‚¹å†…å®¹
    filter: æ¸¯|ğŸ‡­ğŸ‡°|HK|(?i)Hong
 
  #å°æ¹¾èŠ‚ç‚¹
  TW:
    <<: *All
    filter: å°|ğŸ‡¨ğŸ‡³|ğŸ‡¹ğŸ‡¼|æ¹¾|TW|(?i)Taiwan
   
  #ç‹®åŸèŠ‚ç‚¹
  SG:
    <<: *All
    filter: æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|SG|(?i)Singapore
    
  #æ—¥æœ¬èŠ‚ç‚¹
  JP:
    <<: *All
    filter: æ—¥|ğŸ‡¯ğŸ‡µ|ä¸œäº¬|JP|(?i)Japan
    
  #ç¾å›½èŠ‚ç‚¹    
  US:
    <<: *All
    filter: ç¾|ğŸ‡ºğŸ‡²|US|(?i)States|American
    
proxies:
            
proxy-groups:

  - name: èŠ‚ç‚¹é€‰æ‹©
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Rocket.png
    use:
      - All
    proxies:
      - è‡ªåŠ¨ç­›é€‰
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - DIRECT

  - name: è‡ªåŠ¨ç­›é€‰
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Auto.png
    use: 
       - All
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    
  - name: è‹¹æœæœåŠ¡
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Apple.png
    proxies:
      - DIRECT
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹

  - name: æ¸¯å°ç•ªå‰§
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/bilibili.png
    proxies:
      - DIRECT
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹

  - name: å›½é™…åª’ä½“
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/GlobalMedia.png
    proxies:
      - èŠ‚ç‚¹é€‰æ‹©
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
    
  - name: æ¼ç½‘ä¹‹é±¼
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/YoYu.png
    proxies:
      - èŠ‚ç‚¹é€‰æ‹©
      - è‡ªåŠ¨ç­›é€‰
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - DIRECT

  - name: é¦™æ¸¯èŠ‚ç‚¹
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/HK.png
    use:
      - HK
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    
  - name: å°æ¹¾èŠ‚ç‚¹
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/TW.png
    use:
      - TW
    url: "http://www.gstatic.com/generate_204"
    interval: 300
         
  - name: ç‹®åŸèŠ‚ç‚¹
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/SG.png
    use:
      - SG
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    
  - name: æ—¥æœ¬èŠ‚ç‚¹
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/JP.png
    use:
      - JP
    url: "http://www.gstatic.com/generate_204"
    interval: 300

  - name: ç¾å›½èŠ‚ç‚¹
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/US.png
    use:
      - US
    url: "http://www.gstatic.com/generate_204"
    interval: 300

rule-providers:

  Unbreak:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    path: ./ruleset/Unbreak.yaml
    interval: 86400

  AD-Ban:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/Coldvvater/Clash/master/RuleSet/AD-Ban.yaml
    path: ./ruleset/AD-Ban.yaml
    interval: 86400

  Privacy:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/Coldvvater/Clash/master/RuleSet/Privacy.yaml
    path: ./ruleset/Privacy.yaml
    interval: 86400

  Hijacking:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml
    path: ./ruleset/Hijacking.yaml
    interval: 86400

  Streaming:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    path: ./ruleset/Streaming.yaml
    interval: 86400

  StreamingSE:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    path: ./ruleset/StreamingSE.yaml
    interval: 86400

  Global:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    path: ./ruleset/Global.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Apple/Apple.yaml
    path: ./ruleset/Apple.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    path: ./ruleset/China.yaml
    interval: 86400

  LAN:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml
    path: ./ruleset/Lan.yaml
    interval: 86400

rules:
  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,AD-Ban,REJECT
  - RULE-SET,Privacy,REJECT
  - RULE-SET,Hijacking,REJECT
  - RULE-SET,Streaming,å›½é™…åª’ä½“
  - RULE-SET,StreamingSE,æ¸¯å°ç•ªå‰§
  - RULE-SET,Global,èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,Apple,è‹¹æœæœåŠ¡
  - RULE-SET,China,DIRECT
  - RULE-SET,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,æ¼ç½‘ä¹‹é±¼
