# > Stash Config Make by Coldvvater
# > TG Channel: https://t.me/Ison_Channel
# > GitHub: https://github.com/Coldvvater
# > Update Date: 2023.05.03

# > è‡ªé€‰GEOIPåº“å¯ä»¥ä½¿ç”¨: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb

subscribe-url: å¡«ä¸Šä½ çš„è®¢é˜…é“¾æ¥
# > æ›¿æ¢ä¸Šé¢æ–‡å­—ç”¨äºStashè·å–æœºåœºæµé‡ä¿¡æ¯å¹¶åœ¨ä¸»é¡µæ˜¾ç¤º

mixed-port: 7890
# > æœ¬åœ°æ··åˆä»£ç†(httpå’Œsocks5åˆå¹¶ï¼‰ç«¯å£
allow-lan: true
# > å…è®¸å±€åŸŸç½‘è¿æ¥(false/true)
bind-address:
# > ç›‘å¬IPç™½åå•ï¼ˆå½“allow-lanï¼štrueï¼‰ï¼Œåªå…è®¸åˆ—è¡¨è®¾å¤‡
  '*'
# > å…¨éƒ¨è®¾å¤‡
# 192.168.122.11
# > å•ä¸ªip4åœ°å€
# "[aaaa::a8aa:ff:fe09:57d8]"
# > å•ä¸ªip6åœ°å€
mode: rule
# > clashå·¥ä½œæ¨¡å¼ï¼ˆrule/global/directï¼‰
log-level: info
# > æ—¥å¿—ç­‰çº§ï¼ˆinfo/warning/error/debug/silentï¼‰
ipv6: true
# > IP6è§£æå¼€å…³ï¼›å¦‚æœä¸ºfalseï¼Œå°†è¿”å›ip6ç»“æœä¸ºç©º
external-controller: 127.0.0.1:9090
# > æ§åˆ¶å™¨ç›‘å¬åœ°å€
dns:
# > DNSæ¨¡å—è®¾ç½®
  enable: true
# > DNSå¼€å…³(false/true)
  listen: 0.0.0.0:1053
# > DNSç›‘å¬åœ°å€
  ipv6: true
# > IP6è§£æå¼€å…³ï¼›å¦‚æœä¸ºfalseï¼Œå°†è¿”å›ip6ç»“æœä¸ºç©º
  default-nameserver:
# > è§£æéIPçš„dnsç”¨çš„dnsæœåŠ¡å™¨,åªæ”¯æŒçº¯IP
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
  enhanced-mode: fake-ip
# > DNSæ¨¡å¼(redir-host/fake-ip)
  fake-ip-range: 198.18.0.1/16
# > Fake-IPè§£æåœ°å€æ± 
  fake-ip-filter:
# > Fake-ipè¿‡æ»¤ï¼Œåˆ—è¡¨ä¸­çš„åŸŸåè¿”å›çœŸå®ip
    - '*.lan'
# > Local Area Network
    - '+.stun.*.*'
# > Stun Services
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - 'lens.l.google.com'
# > Google Voices
    - '*.n.n.srv.nintendo.net'
# > Nintendo Switch
    - '+.stun.playstation.net'
# > PlayStation
    - 'xbox.*.*.microsoft.com'
# > XBox
    - '*.*.xboxlive.com'
# > Microsoft
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
# > Bilibili CDN
    - '*.mcdn.bilivideo.cn'
  nameserver:
# > é»˜è®¤DNSæœåŠ¡å™¨ï¼Œæ”¯æŒudp/tcp/dot/doh/doq
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query

p: &p {type: http, interval: 42300, health-check: {enable: true, url: http://cp.cloudflare.com/generate_204, interval: 300}}
# > ä»£ç†æä¾›å•†é”šç‚¹

g: &g {type: select, proxies: [Proxy, AutoSelect, Fallback, HongKong, TaiWan, Singapore, Japan, America, Others, DIRECT]}
# > ç­–ç•¥ç»„é”šç‚¹

d: &d {type: select, proxies: [DIRECT, Proxy, AutoSelect, Fallback, HongKong, TaiWan, Singapore, Japan, America, Others]}

proxies: # > æœ¬åœ°æœåŠ¡å™¨

u: &u {type: select, use: [Subs]}
# > è®¢é˜…å¼•ç”¨é”šç‚¹

proxy-providers: # > ä»£ç†æä¾›å•†(è¿œç¨‹è®¢é˜…)
  subs:
    <<: *p
    url: ""
    path: ./proxy-providers/subs.yaml
# 1. è¯·ä½¿ç”¨Clashç±»å‹è®¢é˜…é“¾æ¥å¡«å…¥å¼•å·""å†…ä½¿ç”¨, 
# 2. ä½¿ç”¨é€šç”¨è®¢é˜…é“¾æ¥é€šè¿‡Sub-Storeè¿›è¡Œè®¢é˜…è½¬æ¢(ç”¨äºStash)ã€‚

proxy-groups: # > ç­–ç•¥ç»„

# > æ¼ç½‘ä¹‹é±¼
- {name: Final, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Final.png, <<: *g, proxies: [Proxy,DIRECT]}

# > èŠ‚ç‚¹é€‰æ‹©
- {name: Proxy, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Rocket.png, <<: *g, proxies: [AutoSelect,Fallback,HongKong,TaiWan,Singapore,Japan,America,Others]}

# > è‡ªåŠ¨ç­›é€‰
- {name: AutoSelect, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Auto.png, type: url-test, lazy: true, <<: *u}

# > æ•…éšœè½¬ç§»
- {name: Fallback, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Available.png, type: fallback, <<: *u}

# > å›½å¤–ç½‘ç«™
- {name: Global, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Global.png, <<: *g}

# > å›½å†…ç½‘ç«™
- {name: Mainland, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/China_Map.png, <<: *d}

# > YouTube
- {name: YouTube, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/YouTube.png, <<: *g}

# > NETFLIX
- {name: NETFLIX, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Netflix.png, <<: *g}

# > Disney+
- {name: Disney+, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Disney%2B.png, <<: *g}

# > å“”å“©å“”å“©
- {name: BiliBili, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/bilibili.png, <<: *d, proxies: [DIRECT,HongKong,TaiWan]}

# > å£°ç”°éŸ³ä¹
- {name: Spotify, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Spotify.png, <<: *g}

# > æµ·å¤–æŠ–éŸ³
- {name: TikTok, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/TikTok.png, <<: *g}

# > ç”µæŠ¥ä¿¡æ¯
- {name: Telegram, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Telegram_X.png, <<: *g}

# > è‹¹æœæœåŠ¡
- {name: Apple, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Apple.png, <<: *d}

# > è°·æ­ŒæœåŠ¡
- {name: Google, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Google.png, <<: *g}

# > å¾®è½¯æœåŠ¡
- {name: Microsoft, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Microsoft.png, <<: *d}

# > æ¸¸æˆå¹³å°
- {name: Games, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Game.png, <<: *d}

# > å¹¿å‘Šæ‹¦æˆª
- {name: AdBlock, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Advertising.png, <<: *g, proxies: [REJECT,DIRECT]}

# > é¦™æ¸¯èŠ‚ç‚¹
- {name: HongKong, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Hong_Kong.png, <<: *u, filter: "æ¸¯|ğŸ‡­ğŸ‡°|HK|(?i)Hong"}

# > å°æ¹¾èŠ‚ç‚¹
- {name: TaiWan, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/China.png, <<: *u, filter: "å°|ğŸ‡¨ğŸ‡³|ğŸ‡¹ğŸ‡¼|æ¹¾|TW|(?i)Taiwan"}

# > ç‹®åŸèŠ‚ç‚¹
- {name: Singapore, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Singapore.png, <<: *u, filter: "æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|SG|(?i)Singapore"}

# > æ—¥æœ¬èŠ‚ç‚¹
- {name: Japan, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Japan.png, <<: *u, filter: "æ—¥|ğŸ‡¯ğŸ‡µ|ä¸œäº¬|JP|(?i)Japan"}

# > ç¾å›½èŠ‚ç‚¹
- {name: America, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/United_States.png, <<: *u, filter: "ç¾|ğŸ‡ºğŸ‡²|US|(?i)States|American"}

# > å…¶ä»–èŠ‚ç‚¹
- {name: Others, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Airport.png, <<: *u, proxies: [DIRECT]}


rules: # >  GeoSite åˆ†æµè§„åˆ™å¼•ç”¨
  #- GEOSITE,category-ads-all,AdBlock
  # > ğŸ‘†å¹¿å‘Šæ‹¦æˆªï¼Œæœ‰è¯¯æ€ï¼Œé»˜è®¤å…³ï¼ŒæŒ‰éœ€å¯
  - GEOSITE,private,DIRECT
  - GEOSITE,openai,America
  - GEOSITE,youtube,YouTube
  - GEOSITE,netflix,NETFLIX
  - GEOSITE,disney,Disney+
  - GEOSITE,bilibili,BiliBili
  - GEOSITE,spotify,Spotify
  - GEOSITE,tiktok,TikTok
  - GEOSITE,telegram,Telegram
  - GEOSITE,github,Global
  - GEOSITE,bing,Global
  - GEOSITE,twitter,Global
  - GEOSITE,apple,Apple
  - GEOSITE,google,Google
  - GEOSITE,microsoft,Microsoft
  - GEOSITE,epicgames,Games
  - GEOSITE,sony,Games
  - GEOSITE,steam,Games
  - GEOSITE,nintendo,Games
  - GEOSITE,geolocation-!cn,Global
  - GEOSITE,cn,Mainland

  # > GeoIP å›½å®¶ä»£ç è§„åˆ™
  - GEOIP,telegram,Telegram
  - GEOIP,private,DIRECT
  - GEOIP,CN,Mainland
  - MATCH,Final
