# > Stash Config Make by Coldvvater
# > TG Channel: https://t.me/Ison_Channel
# > GitHub: https://github.com/Coldvvater
# > Update Date: 2023.04.14
---

# > è‡ªé€‰GEOIPåº“å¯ä»¥ä½¿ç”¨: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb

subscribe-url: å¡«ä¸Šä½ çš„è®¢é˜…é“¾æ¥
# > æ›¿æ¢ä¸Šé¢æ–‡å­—ç”¨äºStashè·å–æœºåœºæµé‡ä¿¡æ¯å¹¶åœ¨ä¸»é¡µæ˜¾ç¤º

mixed-port: 7890
  # > æœ¬åœ°æ··åˆä»£ç†(httpå’Œsocks5åˆå¹¶ï¼‰ç«¯å£
allow-lan: true
  # > å…è®¸å±€åŸŸç½‘è¿æ¥(false/true)
bind-address:
  # > ç›‘å¬IPç™½åå•ï¼ˆå½“allow-lanï¼štrueï¼‰ï¼Œåªå…è®¸åˆ—è¡¨è®¾å¤‡
  '*'
  # > å…¨éƒ¨è®¾å¤‡
  # 192.168.122.11
  # > å•ä¸ªip4åœ°å€
  # "[aaaa::a8aa:ff:fe09:57d8]"
  # > å•ä¸ªip6åœ°å€
mode: rule
  # > clashå·¥ä½œæ¨¡å¼ï¼ˆrule/global/directï¼‰
log-level: info
  # > æ—¥å¿—ç­‰çº§ï¼ˆinfo/warning/error/debug/silentï¼‰
external-controller: 127.0.0.1:9090
  # > æ§åˆ¶å™¨ç›‘å¬åœ°å€
dns:
  enable: true
  # > DNSå¼€å…³(false/true)
  listen: 0.0.0.0:1053
  # > DNSç›‘å¬åœ°å€
  ipv6: false
  # > IP6è§£æå¼€å…³ï¼›å¦‚æœä¸ºfalseï¼Œå°†è¿”å›ip6ç»“æœä¸ºç©º
  default-nameserver:
  # > è§£æéIPçš„dnsç”¨çš„dnsæœåŠ¡å™¨,åªæ”¯æŒçº¯IP
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
  enhanced-mode: fake-ip
  # > DNSæ¨¡å¼(redir-host/fake-ip)
  fake-ip-range: 198.18.0.1/16
  # > Fake-IPè§£æåœ°å€æ± 
  fake-ip-filter:
  # > Fake-ipè¿‡æ»¤ï¼Œåˆ—è¡¨ä¸­çš„åŸŸåè¿”å›çœŸå®ip
  # > Local Area Network
    - '*.lan'
  # > Stun Services
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
  # > Google Voices
    - 'lens.l.google.com'
  # > Nintendo Switch
    - '*.n.n.srv.nintendo.net'
  # > PlayStation
    - '+.stun.playstation.net'
  # > XBox
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
  # > Microsoft
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
  # > Bilibili CDN
    - '*.mcdn.bilivideo.cn'
  nameserver:
  # > é»˜è®¤DNSæœåŠ¡å™¨ï¼Œæ”¯æŒudp/tcp/dot/doh/doq
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query

p: &p # > Providersé”šç‚¹
  {type: http, interval: 42300, health-check: {enable: true, url: http://cp.cloudflare.com/generate_204, interval: 300}}

f: &f # > ç­–ç•¥ç»„é”šç‚¹
  {type: select, proxies: [Proxy, Auto, Fallback, HongKong, TaiWan, Singapore, Japan, America, Others, DIRECT]}

d: &d
  {type: select, proxies: [DIRECT, Proxy, Auto, Fallback, HongKong, TaiWan, Singapore, Japan, America, Others]}

proxies:
  # > æœ¬åœ°æœåŠ¡å™¨

u: &u # è®¢é˜…å¼•ç”¨é”šç‚¹
  type: select
  use:
  - subs

proxy-providers:
# > è¿œç¨‹è®¢é˜…
  subs:
    <<: *p
    url: ""
    # > è¯·ä½¿ç”¨Clashç±»å‹è®¢é˜…é“¾æ¥å¡«å…¥å¼•å·""å†…ä½¿ç”¨ã€‚
    # > æˆ–å¯ä½¿ç”¨é€šç”¨è®¢é˜…é“¾æ¥é€šè¿‡Sub-Storeè¿›è¡Œè®¢é˜…è½¬æ¢ã€‚

proxy-groups:
  # > ç­–ç•¥ç»„

  - name: Final # > æ¼ç½‘ä¹‹é±¼
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Final.png
    <<: *f
    proxies:
      - Proxy

  - name: Proxy # > èŠ‚ç‚¹é€‰æ‹©
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Rocket.png
    <<: *f
    proxies:
      - Auto
      - Fallback
      - Others

  - name: Auto # > è‡ªåŠ¨ç­›é€‰
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Auto.png
    lazy: true # åœ¨ç­–ç•¥ç»„æ²¡æœ‰è¢«ä½¿ç”¨æ—¶å€™ï¼Œä¸è¿›è¡Œå»¶è¿Ÿæµ‹è¯•
    <<: *u

  - name: Fallback # > æ•…éšœè½¬ç§»
    type: fallback
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Available.png
    <<: *u

  - name: Foreign # > å›½å¤–ç½‘ç«™
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Global.png
    <<: *f

  - name: Domestic # > å›½å†…ç½‘ç«™
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/China_Map.png
    <<: *d

  - name: BiliBili # > å“”å“©å“”å“©
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/bilibili.png
    <<: *d

  - name: Spotify # > å£°ç”°éŸ³ä¹
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Spotify.png
    <<: *f

  - name: TikTok # > æµ·å¤–æŠ–éŸ³
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/TikTok.png
    <<: *f

  - name: OpenAI # äººå·¥æ™ºèƒ½
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Bot.png
    <<: *f

  - name: Telegram # > ç”µæŠ¥ä¿¡æ¯
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Telegram_X.png
    <<: *f

  - name: Apple # > è‹¹æœæœåŠ¡
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Apple.png
    <<: *d

  - name: Microsoft # > å¾®è½¯æœåŠ¡
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Microsoft.png
    <<: *d

  - name: AdBlock # > å¹¿å‘Šæ‹¦æˆª
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Advertising.png
    <<: *f
    proxies:
      - REJECT
      - DIRECT

  - name: HongKong # > é¦™æ¸¯èŠ‚ç‚¹
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Hong_Kong.png
    <<: *u
    filter: (?=.*(æ¸¯|ğŸ‡­ğŸ‡°|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|ç¾)).)*$
    
  - name: TaiWan # > å°æ¹¾èŠ‚ç‚¹
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/China.png
    <<: *u
    filter: (?=.*(å°|ğŸ‡¨ğŸ‡³|ğŸ‡¹ğŸ‡¼|TW|(?i)Taiwan))^((?!(æ¸¯|æ—¥|éŸ©|æ–°|ç¾)).)*$
         
  - name: Singapore # > ç‹®åŸèŠ‚ç‚¹
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Singapore.png
    <<: *u
    filter: (?=.*(å¡|ğŸ‡¸ğŸ‡¬|SG|(?i)Singapore))^((?!(æ¸¯|å°|æ—¥|éŸ©|ç¾)).)*$
    
  - name: Japan # > æ—¥æœ¬èŠ‚ç‚¹
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Japan.png
    <<: *u
    filter: (?=.*(æ—¥|ğŸ‡¯ğŸ‡µ|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$

  - name: America # > ç¾å›½èŠ‚ç‚¹
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/United_States.png
    <<: *u
    filter: (?=.*(ç¾|ğŸ‡ºğŸ‡¸|US|(?i)States|American))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$

  - name: Others # > å…¶ä»–èŠ‚ç‚¹
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Airport.png
    <<: *u
    proxies:
      - DIRECT

rules:
  # > åˆ†æµè§„åˆ™å¼•ç”¨
  #- GEOSITE,category-ads-all,AdBlock
  # > å¹¿å‘Šè§„åˆ™ï¼Œç–‘æœ‰è¯¯æ‹¦ï¼Œé»˜è®¤å…³é—­ï¼ŒæŒ‰éœ€å¯ç”¨
  - GEOSITE,private,DIRECT
  # > Local Area Network
  - GEOSITE,openai,OpenAI
  # > OpenAI ChatGPT
  - GEOSITE,github,Proxy
  # > GitHub
  - GEOSITE,bilibili,BiliBili
  # > å“”å“©å“”å“©
  - GEOSITE,spotify,Spotify
  # > Spotify
  - GEOSITE,tiktok,TikTok
  # > æµ·å¤–æŠ–éŸ³
  - GEOSITE,telegram,Telegram
  # > ç”µæŠ¥ä¿¡æ¯
  - GEOSITE,apple,Apple
  # > è‹¹æœæœåŠ¡
  - GEOSITE,microsoft,Microsoft
  # > å¾®è½¯æœåŠ¡
  - GEOSITE,geolocation-!cn,Foreign
  # > å›½å¤–ç½‘ç«™
  - GEOSITE,cn,Domestic
  # > å›½å†…ç½‘ç«™

  # > GeoIPå›½å®¶åœ°ç†ä½ç½®
  - GEOIP,netflix,Foreign
  # > Netflix
  - GEOIP,telegram,Telegram
  # > Telegram
  - GEOIP,private,DIRECT
  # > Local Area Network
  - GEOIP,CN,DIRECT
  # > China
  - MATCH,Final
