# > Stash Config Make by Coldvvater
# > TG Channel: https://t.me/Ison_Channel
# > GitHub主页: https://github.com/Coldvvater
# > Update Date: 2022.02.10
---
subscribe-url: 填上你的订阅链接
# > 替换上面文字用于Stash获取机场流量信息并在主页显示

mixed-port: 7890
  # > 本地混合代理(http和socks5合并）端口
allow-lan: true
  # > 允许局域网连接(false/true)
bind-address:
  # > 监听IP白名单（当allow-lan：true），只允许列表设备
  '*'
  # > 全部设备
  # 192.168.122.11
  # > 单个ip4地址
  # "[aaaa::a8aa:ff:fe09:57d8]"
  # > 单个ip6地址
mode: rule
  # > clash工作模式（rule/global/direct）
log-level: debug
  # > 日志等级（info/warning/error/debug/silent）
external-controller: 127.0.0.1:9090
  # > 控制器监听地址
dns:
  enable: true
  # > DNS开关(false/true)
  listen: 0.0.0.0:1053
  # > DNS监听地址
  ipv6: false
  # > IP6解析开关；如果为false，将返回ip6结果为空
  default-nameserver:
  # > 解析非IP的dns用的dns服务器,只支持纯IP
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
  enhanced-mode: fake-ip
  # > DNS模式(redir-host/fake-ip)
  fake-ip-range: 198.18.0.1/16
  # > Fake-IP解析地址池
  fake-ip-filter:
  # > Fake-ip过滤，列表中的域名返回真实ip
  # > Local Area Network
    - '*.lan'
  # > Stun Services
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
  # > Google Voices
    - 'lens.l.google.com'
  # > Nintendo Switch
    - '*.n.n.srv.nintendo.net'
  # > PlayStation
    - '+.stun.playstation.net'
  # > XBox
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
  # > Microsoft
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
  # > Bilibili CDN
    - '*.mcdn.bilivideo.cn'
  nameserver:
  # > 默认DNS服务器，支持udp/tcp/dot/doh/doq
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query

  hosts:
  # > host，支持通配符（例如: *.clash.dev, *.foo.*.example.com ）
  # > 不使用通配符的域名优先级高于使用通配符的域名 (例如: foo.example.com > *.example.com > .example.com )
  # > 注意: +.foo.com 的效果等同于 .foo.com 和 foo.com
    '*.tw': 1.1.1.1
    'localhost' : 127.0.0.1
  # > IPv6
    'ip6-localhost': '::1'
    'ip6-loopback': '::1'
  nameserver-policy:
  # > 域名指定 DNS 映射
  # > Firebase Cloud Messaging
    'mtalk.google.com' : 108.177.125.188
  # > Google Dl
    'dl.google.com' : 119.29.29.29
    'dl.l.google.com' : 119.29.29.29
    'update.googleapis.com' : 119.29.29.29
  # > Apple
    'apple.com' : 223.5.5.5
    '*icloud.com' : 223.5.5.5
    '*icloud.com.cn' : 223.5.5.5
    '*testflight.apple.com': 8.8.4.4
  # > Alibaba
    '*.alipay*.com': 223.5.5.5
    '*.alicdn.com': 223.5.5.5
    'aliyun.com': 223.5.5.5
    '*.aliyun.com': 223.5.5.5
    'taobao.com': 223.5.5.5
    '*.taobao.com': 223.5.5.5
    'tmall.com': 223.5.5.5
    '*.tmall.com': 223.5.5.5
  # > JD
    'jd.com': 119.29.29.29
    '*.jd.com': 119.29.29.29
  # > Tencent
    '*.qq.com': 119.29.29.29
    '*.tencent.com': 119.29.29.29
    'weixin.com': 119.29.29.29
    '*.weixin.com': 119.29.29.29
  # > bilibili
    'bilibili.com': 119.29.29.29
    '*.bilibili.com': 119.29.29.29
    'hdslb.com': 119.29.29.29
  # > NetEase
    '163.com': 119.29.29.29
    '*.163.com': 119.29.29.29
    '126.com': 119.29.29.29
    '*.126.com': 119.29.29.29
    '*.126.net': 119.29.29.29
    '*.127.net': 119.29.29.29
    '*.netease.com': 119.29.29.29
  # > xiaomi
    'mi.com': 119.29.29.29
    '*.mi.com': 119.29.29.29
    'xiaomi.com': 119.29.29.29
    '*.xiaomi.com': 119.29.29.29
  # > Baidu
    '*.baidu.com': 119.29.29.29
    '*.bdstatic.com': 119.29.29.29
  # > Others
    '*.unicompayment.com': 119.29.29.29
    '*.ximalaya.com': 119.29.29.29
    '*.vercel.app': 119.29.29.29
    '*.vercel.com': 119.29.29.29
  # > Local Area Network
    '*.lan': system

proxies:
  # > 本地服务器

proxy-providers:
# > 远程订阅
  sub:
    type: http
    url: ""
    # > 请使用Clash类型订阅链接填入引号""内使用。
    # > 或可使用通用订阅链接通过Sub-Store进行订阅转换。
    interval: 3600
    path: ./sub.yaml
    health-check:
      enable: true
      interval: 600
      url: http://cp.cloudflare.com/generate_204

proxy-groups:
  # > 策略组

  - name: Final # > 漏网之鱼
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Final.png
    proxies:
      - Proxy

  - name: Proxy # > 节点选择
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Rocket.png
    proxies:
      - Auto
      - Fallback
      - Others

  - name: Auto # > 自动筛选
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Auto.png
    use: 
       - sub
    url: "http://cp.cloudflare.com/generate_204"
    interval: 300

  - name: Fallback # > 故障转移
    type: fallback
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Available.png
    use:
      - sub
    url: "http://cp.cloudflare.com/generate_204"
    interval: 300

  - name: Foreign # > 国外网站
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Global.png
    proxies: &F
      - Proxy
      - Auto
      - Fallback
      - HongKong
      - TaiWan
      - Singapore
      - Japan
      - America
      - Others
      - DIRECT

  - name: Domestic # > 国内网站
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/China_Map.png
    proxies: &D
      - DIRECT
      - Proxy
      - Auto
      - Fallback
      - HongKong
      - TaiWan
      - Singapore
      - Japan
      - America
      - Others

  - name: BiliBili # > 哔哩哔哩
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/bilibili.png
    proxies:
      *D

  - name: Spotify # > 声田音乐
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Spotify.png
    proxies:
      *F

  - name: TikTok # > 海外抖音
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/TikTok.png
    proxies:
      *F

  - name: Streaming # > 国际媒体
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Streaming.png
    proxies:
      *F

  - name: Telegram # > 电报信息
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Telegram_X.png
    proxies:
      *F

  - name: Apple # > 苹果服务
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Apple.png
    proxies:
      *D

  - name: Microsoft # > 微软服务
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Microsoft.png
    proxies:
      *D

  - name: ADblock # > 广告拦截
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Advertising.png
    proxies:
      - REJECT
      - DIRECT

  - name: HongKong # > 香港节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Hong_Kong.png
    use:
      - sub
    filter: (?=.*(港|🇭🇰|HK|(?i)Hong))^((?!(台|日|韩|新|美)).)*$
    
  - name: TaiWan # > 台湾节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/China.png
    use:
      - sub
    filter: (?=.*(台|🇨🇳|🇹🇼|TW|(?i)Taiwan))^((?!(港|日|韩|新|美)).)*$
         
  - name: Singapore # > 狮城节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Singapore.png
    use:
      - sub
    filter: (?=.*(坡|🇸🇬|SG|(?i)Singapore))^((?!(港|台|日|韩|美)).)*$
    
  - name: Japan # > 日本节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Japan.png
    use:
      - sub
    filter: (?=.*(日|🇯🇵|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$

  - name: America # > 美国节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/United_States.png
    use:
      - sub
    filter: (?=.*(美|🇺🇸|US|(?i)States|American))^((?!(港|台|日|韩|新)).)*$

  - name: Others # > 其他节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Airport.png
    use: 
       - sub
    proxies:
      - DIRECT

rule-providers:
  # > 远程规则集

  Unbreak: # > 规则修正
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    path: ./ruleset/Unbreak.yaml
    interval: 86400

  AD-Ban: # > 广告拦截
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/Coldvvater/Mononoke/master/Stash/RuleSet/AD-Ban.yaml
    path: ./ruleset/AD-Ban.yaml
    interval: 86400

  Privacy: # > 隐私保护
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/Coldvvater/Mononoke/master/Stash/RuleSet/Privacy.yaml
    path: ./ruleset/Privacy.yaml
    interval: 86400

  Hijacking: # > 运营劫持
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml
    path: ./ruleset/Hijacking.yaml
    interval: 86400

  BiliBili: # > 哔哩哔哩
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Media/Bilibili.yaml
    path: ./ruleset/BiliBili.yaml
    interval: 86400

  Spotify: # > 声田音乐
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml
    path: ./ruleset/Spotify.yaml
    interval: 86400

  TikTok: # > 海外抖音
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml
    path: ./ruleset/TikTok.yaml
    interval: 86400

  Streaming: # > 国际媒体
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml
    path: ./ruleset/Streaming.yaml
    interval: 86400

  Telegram: # > 电报信息
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/Coldvvater/Mononoke/master/Stash/RuleSet/ASN_Telegram.yaml
    path: ./ruleset/Telegram.yaml
    interval: 86400

  Foreign: # > 国外网站
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyLite.yaml
    path: ./ruleset/Foreign.yaml
    interval: 86400

  Apple: # > 苹果服务
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml
    path: ./ruleset/Apple.yaml
    interval: 86400

  Microsoft: # > 微软服务
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  Domestic: # > 国内网站
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml
    path: ./ruleset/Domestic.yaml
    interval: 86400

  LAN: # > 局域网
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml
    path: ./ruleset/Lan.yaml
    interval: 86400

  ASN-CN: # > IP-ASN规则
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/Coldvvater/Mononoke/master/Stash/RuleSet/ASN_China.yaml
    path: ./ruleset/ASN-CN.yaml
    interval: 86400

rules:
  # > 分流规则引用
  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,AD-Ban,ADblock
  - RULE-SET,Privacy,ADblock
  - RULE-SET,Hijacking,ADblock
  - RULE-SET,BiliBili,BiliBili
  - RULE-SET,Spotify,Spotify
  - RULE-SET,TikTok,TikTok
  - RULE-SET,Streaming,Streaming
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Foreign,Foreign
  - RULE-SET,Apple,Apple
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Domestic,Domestic
  - RULE-SET,LAN,DIRECT
  # > ASN China 分流，删除注释启用
  #- RULE-SET,ASN-CN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Final
